name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: checkout repo content
        uses: actions/checkout@v2 
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: python script
        run: python main.py

      - name: present working directory
        run: pwd
        
      - name: execute python script
        run: python files/sample.py
          
